# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-08 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Array',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('array_id', models.CharField(max_length=50)),
                ('array_name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('array_ip', models.CharField(max_length=20)),
                ('PRODUCTVERSION', models.CharField(max_length=50)),
                ('patchVersion', models.CharField(max_length=20)),
                ('TOTALCAPACITY', models.IntegerField()),
                ('FREEDISKSCAPACITY', models.IntegerField()),
                ('STORAGEPOOLCAPACITY', models.IntegerField()),
                ('STORAGEPOOLFREECAPACITY', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lun_ID', models.CharField(max_length=50)),
                ('lun_NAME', models.CharField(max_length=30)),
                ('lun_CAPACITY', models.IntegerField()),
                ('lun_WWN', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_ID', models.IntegerField()),
                ('server_name', models.CharField(max_length=50)),
                ('server_IP', models.CharField(max_length=20)),
                ('array_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Array')),
            ],
        ),
        migrations.AddField(
            model_name='lun',
            name='server_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Server'),
        ),
    ]
